services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
      lagoon.service.port: 8080
    # volumes:
    #   - ./app:/app:delegated
    ports:
      - "8080:8080"
